version: '3'

# Define services
services:

  # App Service
  app:
    # Configuration for building the docker image for the service
    build:
      context: . # Use an image built from the specified dockerfile in the current directory.
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8080:8080" # Forward the exposed port 8080 on the container to port 8080 on the host machine
    restart: always
    depends_on:
      - redis # This service depends on redis. Start that first.
      - mariadb
    environment: # Pass environment variables to the service
      REDIS_URL: redis:6379
      MARIA_URL: mariadb:3306
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend

  # Redis Service
  redis:
    image: redis:6.2-alpine
    ports:
      - 6379:6379
    command: redis-server --save 60 1
    restart: always
    networks:
      - backend
  mariadb:
    image: mariadb:10.5
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bugtrack
    networks:
      - backend

networks:
  backend:
